Import('RTT_ROOT')
Import('rtconfig')
from building import *
cwd = GetCurrentDir()
path = [cwd]
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('ftp', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
