import rtconfig
from building import *


cwd     = os.path.join(str(Dir('#')), 'applications')

CPPPATH = [cwd, str(Dir('#'))]


src = Glob('*.c') + Glob('*.cpp')

if GetDepend(['PKG_USING_LOG']):
    src += Glob('log/*.c')
    CPPPATH += [cwd + '/log']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

group = group + SConscript(os.path.join('fota', 'SConscript'))
group = group + SConscript(os.path.join('sw_check', 'SConscript'))
group = group + SConscript(os.path.join('modules', 'SConscript'))

Return('group')
