from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
group   = DefineGroup('fota', src, depend = ['PKG_USING_FOTA'], CPPPATH = CPPPATH)

Return('group')
