// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto
#ifndef GRPC_api_2eproto__INCLUDED
#define GRPC_api_2eproto__INCLUDED

#include "api.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vrssg {

class VisionRecognitionService final {
 public:
  static constexpr char const* service_full_name() {
    return "vrssg.VisionRecognitionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Get supported recognize model list.
    virtual ::grpc::Status ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::vrssg::Meters* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>> AsyncListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>>(AsyncListMetersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>> PrepareAsyncListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>>(PrepareAsyncListMetersRaw(context, request, cq));
    }
    // Recognize by input.
    virtual ::grpc::Status Recognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::vrssg::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>> AsyncRecognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Get supported recognize model list.
      virtual void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Recognize by input.
      virtual void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>* AsyncListMetersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Meters>* PrepareAsyncListMetersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vrssg::Result>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::vrssg::Meters* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>> AsyncListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>>(AsyncListMetersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>> PrepareAsyncListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>>(PrepareAsyncListMetersRaw(context, request, cq));
    }
    ::grpc::Status Recognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::vrssg::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Result>> AsyncRecognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Result>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Result>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vrssg::Result>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, std::function<void(::grpc::Status)>) override;
      void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ListMeters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ListMeters(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Meters* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, std::function<void(::grpc::Status)>) override;
      void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Recognize(::grpc::ClientContext* context, const ::vrssg::Input* request, ::vrssg::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Recognize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vrssg::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>* AsyncListMetersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vrssg::Meters>* PrepareAsyncListMetersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vrssg::Result>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vrssg::Result>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::vrssg::Input& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListMeters_;
    const ::grpc::internal::RpcMethod rpcmethod_Recognize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Get supported recognize model list.
    virtual ::grpc::Status ListMeters(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response);
    // Recognize by input.
    virtual ::grpc::Status Recognize(::grpc::ServerContext* context, const ::vrssg::Input* request, ::vrssg::Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListMeters() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListMeters(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::vrssg::Meters>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Recognize() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::vrssg::Input* request, ::grpc::ServerAsyncResponseWriter< ::vrssg::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListMeters<WithAsyncMethod_Recognize<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ListMeters() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::vrssg::Meters>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::protobuf::Empty* request, ::vrssg::Meters* response) { return this->ListMeters(context, request, response); }));}
    void SetMessageAllocatorFor_ListMeters(
        ::grpc::experimental::MessageAllocator< ::google::protobuf::Empty, ::vrssg::Meters>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::vrssg::Meters>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ListMeters(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ListMeters(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Recognize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vrssg::Input, ::vrssg::Result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vrssg::Input* request, ::vrssg::Result* response) { return this->Recognize(context, request, response); }));}
    void SetMessageAllocatorFor_Recognize(
        ::grpc::experimental::MessageAllocator< ::vrssg::Input, ::vrssg::Result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vrssg::Input, ::vrssg::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Recognize(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ListMeters<ExperimentalWithCallbackMethod_Recognize<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ListMeters<ExperimentalWithCallbackMethod_Recognize<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListMeters() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Recognize() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListMeters() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListMeters(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Recognize() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ListMeters() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListMeters(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ListMeters(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ListMeters(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Recognize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Recognize(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Recognize(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListMeters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListMeters() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::vrssg::Meters>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::vrssg::Meters>* streamer) {
                       return this->StreamedListMeters(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListMeters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListMeters(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::vrssg::Meters* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListMeters(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::vrssg::Meters>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Recognize() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vrssg::Input, ::vrssg::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vrssg::Input, ::vrssg::Result>* streamer) {
                       return this->StreamedRecognize(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::vrssg::Input* /*request*/, ::vrssg::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vrssg::Input,::vrssg::Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListMeters<WithStreamedUnaryMethod_Recognize<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListMeters<WithStreamedUnaryMethod_Recognize<Service > > StreamedService;
};

}  // namespace vrssg


#endif  // GRPC_api_2eproto__INCLUDED
