#light control cmd type
int32 LIGHT_COLOR_CONTROL=0
int32 LIGHT_STYLE_CONTROL=1
int32 LIGHT_BRIGHTNESS_CONTROL=2
int32 LIGHT_CONTROL_RELEASE=3

#light style
int32 LIGHT_STYLE_STABLE=0
int32 LIGHT_STYLE_BREATHE=1
int32 LIGHT_STYLE_FLASHING=2

#light color
int32 LIGHT_CONTROL_RED=1
int32 LIGHT_CONTROL_ORANGE=2
int32 LIGHT_CONTROL_GREEN=3
int32 LIGHT_CONTROL_CYAN=4
int32 LIGHT_CONTROL_BLUE=5
int32 LIGHT_CONTROL_PURPLE=6
int32 LIGHT_CONTROL_WHITE=7

#param
int32 color
int32 style
int32 brightness

int32 cmd

---

bool result
