from building import *

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('src/*.c')

path    = [cwd + '/inc']

group = DefineGroup('Applications', src, depend = ['PKG_USING_SW_CHECK'], CPPPATH = path)

Return('group')
