#ifndef TTS_STRINGS_H_
#define TTS_STRINGS_H_
#include <map>
#include <vector>
class TTSStrings {
public:
    static std::string text(int key);

    enum {TTS_LANGUAGE_ZH = 0 };
    enum {TTS_LANGUAGE_EN = 1 };
    enum {TTS_LANGUAGE_MAX = 2 };

    enum { TTS_KEY_NULL =  -1,
     TTS_KEY_BACK =  0 ,
     TTS_KEY_TURN_LEFT,
     TTS_KEY_TURN_RIGHT,
     TTS_KEY_LOW_BATTERY,
     TTS_KEY_SWU_INFO,
     TTS_KEY_SWU_FINISHED ,
     TTS_KEY_SWU_FAIL_FIRMWARE,
     TTS_KEY_COLLISION,
     TTS_KEY_CHASSIS_UNLOCKING,
     TTS_KEY_CHASSIS_LOCK,
     TTS_KEY_TELECONTROL_POW_ON,
     TTS_KEY_TELECONTROL_POW_OFF,
     TTS_KEY_TELECONTROL_UNLOCK,
     TTS_KEY_TELECONTROL_LOCKING,
     TTS_KEY_PLEASE_UNLOCK,
     TTS_KEY_REMOTE_UNAVAILABLE,
     TTS_KEY_ROCKER_BACK,
     TTS_KEY_SAFE_MODE,
     TTS_KEY_STD_MODE,
     TTS_KEY_EMC_MODE,
     TTS_KEY_PRESS_EMERGENCY,
     TTS_KEY_RELEASE_EMERGENCY,
     TTS_KEY_PWM_CHASSIS_LOCK,
     TTS_KEY_PWM_CHASSIS_UNLOCKING,
     TTS_KEY_HIGH_BATTERY_TEMP_WARN,
     TTS_KEY_HIGH_BATTERY_TEMP_FATAL,
     TTS_KEY_ENTER_PROTECT_MODE,
     TTS_KEY_LEVEL_SENSOR_TRIG,
     TTS_KEY_SYSTEM_SELF_CHECK_NORMAL,
     TTS_KEY_SYSTEM_SELF_CHECK_ABNORMAL,
     TTS_KEY_HIGH_CALL_VOIP_NO_BOUND,
     TTS_KEY_HIGH_CALL_VOIP_TIMEOUT,
     TTS_KEY_HIGH_CALL_VOIP_BUSY,
     //
     TTS_KEY_DOCK_BEGAIN,
     TTS_KEY_DOCK_FAIL,
     TTS_KEY_DOCK_SUCCESS,
     TTS_KEY_LEAVE_UDOCK,
     TTS_KEY_LEAVE_FAIL,
     TTS_KEY_LEAVE_SUCCESS,

     //
     TTS_KEY_SPRAYER_SPRAYING,

     //RC means remote control
     TTS_KEY_RC_CHASSIS_LOCKED_BY_LIDAR,
     TTS_KEY_RC_FRONT_SINGLE_LIDAR_FAILURE,
     TTS_KEY_RC_MULTI_LIDAR_FAILURE,
     TTS_KEY_RC_REAR_LIDAR_FAILURE,
     TTS_KEY_RC_AFTER_CHASSIS_LOCKED_BY_LIDAR,
     TTS_KEY_STEEP_SLOPE,
     TTS_KEY_ENCOUNTER_OBSTACLE,
     TTS_KEY_REMOTE_CONTROL_CHASSIS,
     TTS_KEY_SHTTPD_CONTROL_CHASSIS,
     TTS_KEY_PC_CONTROL_CHASSIS,
     TTS_KEY_RECHARGE_CONTROL_CHASSIS,
     TTS_KEY_TEST_CONTROL_CHASSIS,
     TTS_KEY_NAVIGATION_CONTROL_CHASSIS,
     TTS_KEY_TIMEOUT_CONTROL_CHASSIS,
     TTS_KEY_SERVER_ON_CONNECT,
     TTS_KEY_SERVER_DISCONNECT
    };

};
#endif //TTS_STRINGS_H_
